### ISSUE TITLE
Make it possible to configure the basepath instead of the hard coded default "/api/v1/"

### ISSUE THREAD

**Issue by oliemansm** [mittwald/go-powerdns#20]
We're using Caddy webserver and we have a PowerDNS compatible DNS server. We'd like to use wildcard certificates and for that we'd like to use the available powerdns module: https://github.com/caddy-dns/powerdns. This library is in the end the one providing the functionality to that module to communicate with the PowerDNS server.

When I try to configure it defining the server-url, server-id and api-token I noticed that the server-url is actually the server-host and that the base-path is hardcoded, even though it's always "/api/v1/server" or at least "/api/v1": https://github.com/search?q=repo%3Amittwald%2Fgo-powerdns+%2Fapi%2Fv1&type=code&p=2.

However, the API of the PowerDNS compatible server we're dealing with uses a different base path, since they integrated that API in their own full portal API, so their base path is actually: "/api/v2/drs/domain/dns/servers".

So my question is whether you're open to the idea to make that value configurable, while keeping it's current value as the default. That way no existing usage will break, but it will allow people like me to override it.

I don't have any experience with Go, but I'm happy to contribute if you're open to it.

**UPDATE:** Actually being able to flag to add that path or not to the URL would suffice, seeing the `baseURL` accepts the full URL, so could just simply be included there.

**Comment by martin-helmich** [comment]
Hey Michiel!  👋   Thanks for the suggestion; this sound like a good idea. And contributions are always welcome. 🙂 

That change would probably require a bit of grunt work, because the API base path is individually hardcoded in every single request function (in hindsight, not the smartest choice 🙄). Ideally, I would opt to just make the `/api/v1` part of the base URL, which is difficult to implement without a breaking change, however.

Maybe like this:

1. When [constructing the `pdnshttp.Client`](https://github.com/mittwald/go-powerdns/blob/f0c972181db9068e8405d01aa10dd43f59b25836/pdnshttp/client.go#L21-L30), check if `baseURL` contains a path (if not, or if it's only `/`, default it to `/api/v1`; otherwise just leave it as-is).
2. Remove the `/api/v1` path prefix from any individual request functions which invoke `NewRequest` on the client.

What do you think?

**Comment by oliemansm** [comment]
Thanks for the quick response! I was considering exactly the same approach. I'll give it a "go" ;)

**Comment by oliemansm** [comment]
I've created a PR for this: https://github.com/mittwald/go-powerdns/pull/21
